up f14

diff --git a/processes_and_signals/11-manage_my_process b/processes_and_signals/11-manage_my_process
--- a/processes_and_signals/11-manage_my_process
+++ b/processes_and_signals/11-manage_my_process
@@ -13,8 +13,16 @@ start()
 	fi
 	
 	./manage_my_process &
-	echo $! > "$PID_FILE"
-	echo "$PROCESS_NAME started"
+	
+	    PID=$!
+
+    if [ -n "$PID" ]; then
+        echo "$PROCESS_NAME started with PID: $PID"
+        echo $PID > "$PID_FILE"
+    else
+        echo "Failed to start $PROCESS_NAME."
+        exit 1
+    fi
 }
 
 stop() 
